user_add: takeoff
user_pass: $6$3/DDs00Y/MtoCgcR$c.IOza1fegsW2g/vZvdkod51N9e0IirsCMq1ZRMhDEgh5sa5p0HpILf5s2w6XOJKAtAv.MSiD5rqwQezLfN7J0
app_user: nikita
app_name: helloworld
app_dir: '/opt/{{ app_name }}'
app_log_dir: '/opt/{{ app_name }}/log'
app_repo: https://github.com/shmykyta/helloworld.git
path_ssl: '/etc/ssl'
nginx_cert_path: '/etc/nginx/ssl'
ssh_conf: '/etc/ssh/sshd_config'
