---
- name: 'clone app from repo'
  git:
    repo: '{{ app_repo }}'
    dest: '{{ app_dir }}/{{ app_name }}'
    update: yes
  become: yes
  become_user: '{{ app_user }}'

- name: 'install modules in a virtualenv'
  pip:
    requirements: '{{ app_dir }}/{{ app_name }}/requirements.txt'
    virtualenv: '{{ app_dir }}/{{ app_name }}/env'
    virtualenv_python: python3

- name: 'Change user on {{ app_user }} on env'
  file:
    dest: '{{ app_dir }}/{{ app_name }}/env'
    owner: '{{ app_user }}'
    group: '{{ app_user }}'
    mode: 0755
    recurse: yes

- name: template systemd service config
  template:
    src: 'app.service.j2'
    dest: '/etc/systemd/system/{{ app_name }}.service'
  notify: restart {{ app_name }}
  become: yes
  become_user: '{{ app_user }}'