---
- meta: end_play
  when: ansible_distribution != 'Ubuntu'

- name: 'Add group {{ user_add }}'
  group:
    name: '{{ user_add }}'
    state: present

- name: 'Add {{ user_add }} and add it to sudo'
  user:
    name: '{{ user_add }}'
    password: '{{ user_pass }}'
    group: '{{ user_add }}'
    generate_ssh_key: yes
    groups: sudo
    createhome: yes
    state: present
  become: yes
  become_method: 'sudo'

- name: 'Allow connect using login and pass'
  lineinfile:
    path: '{{ ssh_conf }}'
    regexp: 'PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
    state: present
  become: true
  become_method: sudo

# module service don't work properly, so just used some shell

- name: 'restart ssh service'
  shell: "sudo -i -- sh -c 'service ssh restart'"

- name: 'Wait for ssh will avaible'
  wait_for: port=22 state=started

- name: 'Make folders for app'
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ app_user }}'
    group: '{{ app_user }}'
  with_items:
    - '{{ log_dir }}'
    - '{{ app_dir }}'
    - '{{ app_log_dir }}'

- name: 'install packages'
  apt:
    name: python3,uwsgi,nginx-full,git,systemd,python3-pip,python3-dev,nginx,python-pip,python-dev
    state: latest
    update_cache: yes

- name: 'Upgrade pip'
  pip:
    name: pip
    extra_args: --upgrade

- name: 'Update and upgrade apt packages'
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: 'install various libraries with pip'
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - virtualenv
    - supervisor
    - uwsgi
    - PyOpenSSL
    - setuptools